# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

function sourceIfExists()
{
    local file=$1
    if [[ -f $file ]]
    then
        . $file
    fi
}

# Path to whom other paths are relative to
#confs_folder=~/Confs/bash_files
path_to_bashrc=$(readlink -f ~/.bashrc)
confs_folder=$(dirname $path_to_bashrc)/

sourceIfExists ${confs_folder}/envtests
sourceIfExists ${confs_folder}/defines
sourceIfExists ${confs_folder}/exports
sourceIfExists ${confs_folder}/prompt
sourceIfExists ${confs_folder}/aliases
sourceIfExists ~/.local_aliases
sourceIfExists ~/.fzf.bash
