# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

function sourceIfExists()
{
    local file=$1
    if [[ -f $file ]]
    then
        . $file
    fi
}

# Path to whom other paths are relative to
#confs_folder=~/Confs/bash_files
path_to_bashrc=$(/bin/readlink -f ~/.bashrc)
confs_folder=$(/bin/dirname $path_to_bashrc)/
export MY_CONF_FOLDER="$confs_folder"
export MY_BASHRC="$path_to_bashrc"

sourceIfExists ${confs_folder}/envtests
sourceIfExists ${confs_folder}/defines
sourceIfExists ${confs_folder}/exports
sourceIfExists ${confs_folder}/prompt
sourceIfExists ${confs_folder}/aliases
sourceIfExists ~/.local_aliases
sourceIfExists ~/.fzf.bash
[ -d "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

PATH="/opt/local/bin:$PATH"
PATH="$HOME/.bin:$PATH"

which fzf &> /dev/null
if [[ $? -eq 0 ]]
then
	eval "$(fzf --bash)"
fi

# Added by LM Studio CLI (lms)
PATH="$PATH:/home/neurosys/.lmstudio/bin"
# End of LM Studio CLI section
