# Path to your oh-my-zsh installation.

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"
#setopt APPEND_HISTORY



# User configuration

# export MANPATH="/usr/local/man:$MANPATH"


path_to_conf_folder=$( readlink -f ~/.zshrc )
modules_folder=$(dirname $path_to_conf_folder)


if [ -f ${modules_folder}/envtests ]
then
    . ${modules_folder}/envtests
fi

if [ -f ${modules_folder}/defines ]
then
    . ${modules_folder}/defines
fi

if [ -f ${modules_folder}/exports ]
then
    . ${modules_folder}/exports
fi

if [ -f ${modules_folder}/aliases ]
then
    . ${modules_folder}/aliases
fi


if [ -f ~/.local_aliases ]
then
    . ~/.local_aliases
fi

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=${modules_folder}/zsh/

# List of plugins
# zsh-syntax-highlighting - Provides command line highlighting for cmd name, globing and others
# colored-man-pages       - Adds colors to man pages
# rand-quote              - Downloads a quote when launching % quote
# colorize                - Tries to highlighting file content based on extension or content
#                           requires pygmentize (run as cat)
# cp                      - Use rsync to copy files and get progress bar (run as cpv)
# sudo                    - Presc Esc-Esc to run the last command with sudo as prefix
# vim-interaction         - Open a file in an already running gvim session (run as callvim or simply v)
# calc                    - Allows simple calculator on command line (run as = <operations>) requires bc
# bgnotify                - ???
# common-aliases          - Useful set of aliases (needs to soak)

if [[ $is_cygwin -eq 1 ]]
then
    plugins=(zsh-syntax-highlighting colored-man-pages colorize cp git git-extras k jira vim-interaction bgnotify mvn screen)
    ZSH_THEME="myjtriley"
    #ZSH_THEME="candy"
else
    ZSH_THEME="myjtriley"
   #ZSH_THEME="random"
    plugins=(zsh-syntax-highlighting colored-man-pages colorize cp sudo vim-interaction bgnotify k git git-extras jira mvn)
fi

bgnotify_treshold=1
DISABLE_AUTO_UPDATE="false"
export ZSH=${modules_folder}/zsh/oh-my-zsh
source $ZSH/oh-my-zsh.sh

# oh-my zsh activates a shared history among the instances and I don't like that
unset SHARE_HISTORY


# Print a status, but except the scp connections, otherwise scp transfers will fail
if [ "$TERM" != "dumb" ] && [ -f ${modules_folder}/print_status ]
then
    . ${modules_folder}/print_status
fi

#. ~/oh-my-zsh/plugins/z/z.sh
. $ZSH/plugins/z/z.sh

. ${modules_folder}/zsh/plugins/calc.plugin.zsh/calc.plugin.zsh

# The following lines were added by compinstall

#zstyle ':completion:*' completer _complete _ignored
#zstyle :compinstall filename '/home/camza/.zshrc'
#
autoload -Uz compinit
compinit
## End of lines added by compinstall
## Lines configured by zsh-newuser-install
#HISTFILE=~/.zsh-histfile
#HISTSIZE=99999
#SAVEHIST=99999
#setopt appendhistory
#unsetopt beep
#bindkey -e
# End of lines configured by zsh-newuser-install

# Cusotomize zsh-syntax-highlighting (get ride of the dark blue color, to turn it off, set it to none)
ZSH_HIGHLIGHT_STYLES[globbing]='fg=cyan,bold'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# vim:syn=sh

