#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]
then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]
then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]
then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]
then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]
then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ;
    do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set fail primary/secondary GPU
# > xrandr --listproviders
# > Providers: number : 2
# > Provider 0: id: 0x7b cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 2 outputs: 4 associated providers: 0 name:Intel
# > Provider 1: id: 0x55 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 6 outputs: 0 associated providers: 0 name:TURKS @ pci:0000:01:00.0
xrandr --setprovideroffloadsink 0x55 0x7b
# use 'glxinfo | grep "OpenGL"' to identify the graphics used currently
# Use DRI_PRIME=1 <cmd> to have the app started use the better card
epxort DRI_PRIME=1

# Fix two monitor setup
#xrandr --output HDMI-1 --auto --left-of LVDS-1 --output LVDS1 --auto --scale 1.0001x1.0001

# Set wallpaper
feh --bg-center ~/Pictures/luis_royo_fallenangelI.jpg

# Make Caps-Lock a new Ctrl
setxkbmap -layout us -option ctrl:nocaps

# Prepare support for transparency
xcompmgr &
transset 0.2

# Enable volume keys
xbindkeys

dwm

