# Path to your oh-my-zsh installation.
  export ZSH=/home/camza/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
#ZSH_THEME="bira"
#ZSH_THEME="bureau"
ZSH_THEME="rkj-repos"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting colored-man-pages colorize rand-quote cp sudo k vim-interaction calc)

# User configuration

  export PATH="/home/camza/.local/bin:/home/camza/bin:/home/camza/.local/bin:/home/camza/bin:/home/camza/local/bin:/usr/lib64/qt-3.3/bin:/home/camza/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias ls='ls -a --color=auto'
alias ll='ls -lah --color=auto'


# Display the size (in MB) each item (file or folder) in this folder takes up and display them in a sorted order
alias lu='find -maxdepth 1 -exec du -sm {} \; | sed -e "s;^\([0-9]\+\)\t\+;\1 M\t;" | sort -rn'

alias wget='wget -nc --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1309.0 Safari/537.17" -m --convert-links --page-requisites --no-parent -e robots=off'
# -nc no clobber (Don't overwrite an already file, nor save it as file.nr1 nr2 ... 
# --wait=20 wait 20 seconds between requests
# --random-wait randomize the wait between 0.5 * wait - 1.5 * wait time
# --user-agent=  Name of the user-agent 
# --convert-links after download convert links for local usage
# -m mirrors the url
# --page-requisites load the resources necesarry to view the page as it is on the web
# --no-parent don't ascend to parent directory
# -e robots=off ignore the contents of robots.txt

# Run Firefox with different profiles (Worker and Organizer)
alias fworker='firefox -P Worker -no-remote &> /dev/null &'
alias forganizer='firefox -P Organizer -no-remote &> /dev/null &'


alias gdb='gdb -q'

alias ds30me='sshpass -p salutare ssh camza@77.81.122.58'


alias ttyds='sudo minicom --baudrate 115200 --device /dev/ttyUSB1 --color=on'
alias ttyv2='sudo minicom --baudrate 38400  --device /dev/ttyUSB0 --color=on'

#alias terminate='kill -15'
function terminate()
{
    kill -15 $(pgrep $1)
}

. ~/.oh-my-zsh/plugins/z/z.sh
